# Generated by Django 2.1.1 on 2018-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0003_auto_20181113_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one',
            name='GPValue1_million_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='one',
            name='GPValue1_million_slc',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='one',
            name='GPValue2_million_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='one',
            name='GPValue2_million_slc',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='one',
            name='GPValue_thousand_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='one',
            name='NPValue_thousand_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_one',
            name='GPValue1_million_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_one',
            name='GPValue1_million_slc',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_one',
            name='GPValue2_million_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_one',
            name='GPValue2_million_slc',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_one',
            name='GPValue_thousand_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_one',
            name='NPValue_thousand_dollar',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prod_area',
            name='org_val',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prod_area',
            name='pred_val',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
