# Generated by Django 2.1.1 on 2018-11-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0007_auto_20181113_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='one',
            old_name='GPValue1_million_dollar',
            new_name='Gross_Production_Value_constant_2004_2006_1000_dollar',
        ),
        migrations.RenameField(
            model_name='one',
            old_name='GPValue1_million_slc',
            new_name='Gross_Production_Value_constant_2004_2006_million_SLC',
        ),
        migrations.RenameField(
            model_name='one',
            old_name='GPValue2_million_dollar',
            new_name='Gross_Production_Value_constant_2004_2006_million_US_dollar',
        ),
        migrations.RenameField(
            model_name='one',
            old_name='GPValue2_million_slc',
            new_name='Gross_Production_Value_current_million_SLC',
        ),
        migrations.RenameField(
            model_name='one',
            old_name='GPValue_thousand_dollar',
            new_name='Gross_Production_Value_current_million_US_dollar',
        ),
        migrations.RenameField(
            model_name='one',
            old_name='NPValue_thousand_dollar',
            new_name='Net_Production_Value_constant_2004_2006_1000_dollar',
        ),
        migrations.RenameField(
            model_name='pred_one',
            old_name='GPValue1_million_dollar',
            new_name='Gross_Production_Value_constant_2004_2006_1000_dollar',
        ),
        migrations.RenameField(
            model_name='pred_one',
            old_name='GPValue1_million_slc',
            new_name='Gross_Production_Value_constant_2004_2006_million_SLC',
        ),
        migrations.RenameField(
            model_name='pred_one',
            old_name='GPValue2_million_dollar',
            new_name='Gross_Production_Value_constant_2004_2006_million_US_dollar',
        ),
        migrations.RenameField(
            model_name='pred_one',
            old_name='GPValue2_million_slc',
            new_name='Gross_Production_Value_current_million_SLC',
        ),
        migrations.RenameField(
            model_name='pred_one',
            old_name='GPValue_thousand_dollar',
            new_name='Gross_Production_Value_current_million_US_dollar',
        ),
        migrations.RenameField(
            model_name='pred_one',
            old_name='NPValue_thousand_dollar',
            new_name='Net_Production_Value_constant_2004_2006_1000_dollar',
        ),
        migrations.RenameField(
            model_name='three',
            old_name='domestic',
            new_name='Domestic',
        ),
        migrations.RenameField(
            model_name='three',
            old_name='export',
            new_name='Export',
        ),
        migrations.RenameField(
            model_name='three',
            old_name='imports',
            new_name='Imports',
        ),
        migrations.RenameField(
            model_name='three',
            old_name='production',
            new_name='Production',
        ),
        migrations.RenameField(
            model_name='three',
            old_name='seed',
            new_name='Seed',
        ),
        migrations.RenameField(
            model_name='three',
            old_name='stock',
            new_name='Stock',
        ),
    ]
