# Generated by Django 2.1.1 on 2018-11-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0008_auto_20181113_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='two',
            old_name='area',
            new_name='area_harvested',
        ),
    ]
