# Generated by Django 2.1.1 on 2018-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0009_auto_20181113_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='pred_three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('imports', models.IntegerField()),
                ('exports', models.IntegerField()),
                ('production', models.IntegerField()),
            ],
        ),
    ]
