# Generated by Django 2.1.1 on 2018-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0010_pred_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pred_three',
            name='exports',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_three',
            name='imports',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pred_three',
            name='production',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
