# Generated by Django 2.1.1 on 2018-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(default='aaa@bb.c', max_length=254)),
                ('suggestion', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateTimeField(verbose_name='signup date')),
                ('time of signin', models.TimeField()),
                ('remember_later', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateTimeField(verbose_name='signup date')),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(default='aaa@bb.c', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(default='male', max_length=50)),
            ],
        ),
    ]
